version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: tuplaus-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: tuplaus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tuplaus_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./tuplaus-backend
    container_name: tuplaus-backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/tuplaus_db?schema=public
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
      
volumes:
  postgres_data:
